# Generated by Django 5.1.7 on 2025-03-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('carga_horaria', models.DecimalField(decimal_places=2, max_digits=4)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
